<h1 style="color:#4CE895"> Get Datasets from various sources </h1>

In [2]:
# Sets an environment variable to suppress log messages from TensorFlow with level 2 or lower
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [3]:
import seaborn as sns
import pandas as pd
import nltk
from keras.datasets import mnist
import openml
from sklearn.datasets import load_iris
import torchvision.datasets as datasets

In [4]:
%%script echo Skipping. It may generate conflicts in pip caused by "protobuf" version => Tensorboard
import tensorflow-datasets as tfds

Skipping. It may generate conflicts in pip caused by protobuf version => Tensorboard


In [9]:
tips = sns.load_dataset("tips") 

In [36]:
df_panda = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
df_panda

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
%%script echo Skipping. Avoid downloading all the times 
# Download the Brown Corpus
nltk.download("brown")  
from nltk.corpus import brown

Skipping. Avoid downloading all the times


In [38]:
# Load the MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()  
X_train[:2]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [6]:
%%script echo Skipping since tensorflow-datasets (tfds) it is not installed 
# Load the Iris dataset
dataset = tfds.load("iris")  

Skipping since tensorflow-datasets (tfds) it is not installed


In [21]:
# Load the Iris dataset from OpenML
datasetopen = openml.datasets.get_dataset(61)  
datasetopen

OpenML Dataset
Name..........: iris
Version.......: 1
Format........: ARFF
Upload Date...: 2014-04-06 23:23:39
Licence.......: Public
Download URL..: https://api.openml.org/data/v1/download/61/iris.arff
OpenML URL....: https://www.openml.org/d/61
# of features.: 5
# of instances: 150

In [34]:
data_table = datasetopen.get_data()
data_table

(     sepallength  sepalwidth  petallength  petalwidth           class
 0            5.1         3.5          1.4         0.2     Iris-setosa
 1            4.9         3.0          1.4         0.2     Iris-setosa
 2            4.7         3.2          1.3         0.2     Iris-setosa
 3            4.6         3.1          1.5         0.2     Iris-setosa
 4            5.0         3.6          1.4         0.2     Iris-setosa
 ..           ...         ...          ...         ...             ...
 145          6.7         3.0          5.2         2.3  Iris-virginica
 146          6.3         2.5          5.0         1.9  Iris-virginica
 147          6.5         3.0          5.2         2.0  Iris-virginica
 148          6.2         3.4          5.4         2.3  Iris-virginica
 149          5.9         3.0          5.1         1.8  Iris-virginica
 
 [150 rows x 5 columns],
 None,
 [False, False, False, False, True],
 ['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'])

In [27]:
# Load the Iris dataset
iris = load_iris()  
print(f"type of iris dataset {type(iris)}")
print(iris.data[:10])
print()
print(iris.target[:10])

type of iris dataset <class 'sklearn.utils._bunch.Bunch'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

[0 0 0 0 0 0 0 0 0 0]


In [18]:
%%script echo Skip to not download again
# Load the MNIST training dataset
mnist_train = datasets.MNIST(root='data', train=True, download=True)  

100%|██████████| 9912422/9912422 [00:00<00:00, 11609001.35it/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 34423328.74it/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 2613768.91it/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 3674161.77it/s]


Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [35]:
mnist_train.data[:2]

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.uint8)

`From Kaggle`

import os <br>
import kaggle <br>
os.environ['KAGGLE_USERNAME'] = 'your_username' <br>
os.environ['KAGGLE_KEY'] = 'your_api_key' <br>

\# Replace 'username/dataset-name' with the actual dataset you want to download <br>
dataset_name = 'username/dataset-name' <br>

\# Specify the directory where you want to download the dataset <br>
download_dir = '/path/to/your/dataset/directory' <br>

\# Use the Kaggle API to download the dataset <br>
kaggle.api.dataset_download_files(dataset_name, path=download_dir, unzip=True) <br>